MVCproyecto/Models/ClienteProducto.cs
using System.ComponentModel.DataAnnotations;

namespace MVCproyecto.Models
{
    public class Cliente
    {
        public int id { get; set; }
        public string? cedula { get; set; }
        public string? foto { get; set; }
        public string? nombre { get; set; }
        public string? apellido { get; set; }
        public string? email { get; set; }
        public string? telefono { get; set; }
    }

    public class Producto
    {
        public int id { get; set; }
        public string? codigo { get; set; }
        public string? foto { get; set; }
        public string? nombre { get; set; }
        public string? descripcion { get; set; }
        public string? categoria { get; set; }
        public float precio { get; set; }
    }

    public class Compra
    {
        public int id { get; set; }
        public string? fecha { get; set; }
        public string? Usuario { get; set; }
        public string? Producto { get; set; }
        public string? cantidad { get; set; }
        public float precio { get; set; }
    }
}

MVCproyecto/Models/ErrorViewModel.cs
namespace MVCproyecto.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MVCproyecto/Controllers/ClienteController.cs
using Microsoft.AspNetCore.Mvc;
using MVCproyecto.Models;

namespace MVCproyecto.Controllers
{
    public class ClienteController : Controller
    {

        private readonly APIGateway _api;

        public ClienteController(APIGateway api)
        {
            this._api = api;
        }
        //Crear una lista de lo que ve
        public IActionResult Index()
        {
            List<Cliente> clientes;
            clientes = _api.ListCliente();
            return View(clientes);
        }

        [HttpGet]
        public IActionResult Create() {
            Cliente cliente = new Cliente();
            return View(cliente);
        }

        [HttpPost]
        public IActionResult Create(Cliente cliente)
        {
            _api.CrearCliente(cliente);
            return RedirectToAction("Index");
        }

        public IActionResult Details (int id)
        {
            Cliente cliente;

            cliente = _api.GetCliente(id);
            
            return View(cliente);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            Cliente cliente;
            cliente = _api.GetCliente(id);
            return View(cliente);
        }

        [HttpPost]
        public IActionResult Edit(Cliente cliente)
        {
            _api.ActualizarCliente(cliente);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            Cliente cliente;
            cliente = _api.GetCliente(id);
            return View(cliente);
        }

        [HttpPost]
        public IActionResult Delete(Cliente cliente)
        {
            _api.EliminarCliente(cliente.id);
            return RedirectToAction("Index");
        }
    }
}

MVCproyecto/Controllers/CompraController.cs
using Microsoft.AspNetCore.Mvc;
using MVCproyecto.Models;

namespace MVCproyecto.Controllers
{
    public class CompraController : Controller
    {
        private readonly APIGateway _api;

        public CompraController(APIGateway api)
        {
            _api = api;
        }

        //Crear una lista de lo que ve
        public IActionResult Index()
        {
            List<Compra> compras;
            compras = _api.ListCompra();
            return View(compras);
        }

        [HttpGet]
        public IActionResult Create()
        {
            Compra compra = new Compra();
            return View(compra);
        }

        [HttpPost]
        public IActionResult Create(Compra compra)
        {
            _api.CrearCompra(compra);
            return RedirectToAction("Index");
        }

        public IActionResult Details(int id)
        {
            Compra compra;

            compra = _api.GetCompra(id);

            return View(compra);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            Compra compra;
            compra = _api.GetCompra(id);
            return View(compra);
        }

        [HttpPost]
        public IActionResult Edit(Compra compra)
        {
            _api.ActualizarCompra(compra);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            Compra compra;
            compra = _api.GetCompra(id);
            return View(compra);
        }

        [HttpPost]
        public IActionResult Delete(Compra compra)
        {
            _api.EliminarCompra(compra.id);
            return RedirectToAction("Index");
        }
    }
}

MVCproyecto/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MVCproyecto.Models;
using System.Diagnostics;

namespace MVCproyecto.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MVCproyecto/Controllers/ProductoController.cs
using Microsoft.AspNetCore.Mvc;
using MVCproyecto.Models;

namespace MVCproyecto.Controllers
{
    public class ProductoController : Controller
    {
        private readonly APIGateway _api;

        public ProductoController(APIGateway api)
        {
            this._api = api;
        }
        //Crear una lista de lo que ve
        public IActionResult Index()
        {
            List<Producto> producto;
            producto = _api.ListProducto();
            return View(producto);
        }

        [HttpGet]
        public IActionResult Create()
        {
            Producto producto = new Producto();
            return View(producto);
        }

        [HttpPost]
        public IActionResult Create(Producto producto)
        {
            _api.CrearProducto(producto);
            return RedirectToAction("Index");
        }

        public IActionResult Details(int id)
        {
            Producto producto = new Producto();

            producto = _api.GetProducto(id);

            return View(producto);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            Producto producto;
            producto = _api.GetProducto(id);
            return View(producto);
        }

        [HttpPost]
        public IActionResult Edit(Producto producto)
        {
            _api.ActualizarProducto(producto);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            Producto producto;
            producto = _api.GetProducto(id);
            return View(producto);
        }

        [HttpPost]
        public IActionResult Delete(Producto producto)
        {
            _api.EliminarProducto(producto.id);
            return RedirectToAction("Index");
        }
    }
}

MVCproyecto/Views/Cliente/Create.cshtml
@model MVCproyecto.Models.Cliente

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Cliente</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @*<div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="cedula" class="control-label"></label>
                <input asp-for="cedula" class="form-control" />
                <span asp-validation-for="cedula" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="nombre" class="control-label"></label>
                <input asp-for="nombre" class="form-control" />
                <span asp-validation-for="nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="apellido" class="control-label"></label>
                <input asp-for="apellido" class="form-control" />
                <span asp-validation-for="apellido" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="foto" class="control-label"></label>
                <input asp-for="foto" class="form-control" />
                <span asp-validation-for="foto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="email" class="control-label"></label>
                <input asp-for="email" class="form-control" />
                <span asp-validation-for="email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="telefono" class="control-label"></label>
                <input asp-for="telefono" class="form-control" />
                <span asp-validation-for="telefono" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-info" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVCproyecto/Views/Cliente/Delete.cshtml
@model MVCproyecto.Models.Cliente

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Cliente</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.cedula)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.cedula)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.apellido)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.apellido)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.foto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.foto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.telefono)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.telefono)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a class="btn btn-info" asp-action="Index">Back to List</a>
    </form>
</div>

MVCproyecto/Views/Cliente/Details.cshtml
@model MVCproyecto.Models.Cliente

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Cliente</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.cedula)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.cedula)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.apellido)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.apellido)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.foto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.foto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.telefono)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.telefono)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }, 
    new { onclick = "return confirmation();", @class = "btn btn-primary"}) |
    <a class="btn btn-info" asp-action="Index">Back to List</a>
</div>

MVCproyecto/Views/Cliente/Edit.cshtml
@model MVCproyecto.Models.Cliente

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Cliente</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="id" class="control-label"></label>
                <input asp-for="id" class="form-control" readonly/>
                <span asp-validation-for="id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="cedula" class="control-label"></label>
                <input asp-for="cedula" class="form-control" />
                <span asp-validation-for="cedula" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="nombre" class="control-label"></label>
                <input asp-for="nombre" class="form-control" />
                <span asp-validation-for="nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="apellido" class="control-label"></label>
                <input asp-for="apellido" class="form-control" />
                <span asp-validation-for="apellido" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="foto" class="control-label"></label>
                <input asp-for="foto" class="form-control" />
                <span asp-validation-for="foto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="email" class="control-label"></label>
                <input asp-for="email" class="form-control" />
                <span asp-validation-for="email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="telefono" class="control-label"></label>
                <input asp-for="telefono" class="form-control" />
                <span asp-validation-for="telefono" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-info" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVCproyecto/Views/Cliente/Index.cshtml
@model IEnumerable<MVCproyecto.Models.Cliente>

@{
    ViewData["Title"] = "Index";
}

<h1>Clientes</h1>
<style>
    h1 {
        color: white;
        font-family: 'Times New Roman', Times, serif;
    }
</style>

<p>
    <a class="btn btn-success" asp-action="Create">Crear nuevo cliente</a>
</p>
<table class="table table-dark">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.cedula)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.apellido)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.telefono)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.cedula)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.apellido)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.email)
            </td>
            <td>
                @Html.DisplayNameFor(model => model.telefono)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new {id=item.id }, 
                new { onclick = "return confirmation();", @class = "btn btn-primary"}) |
                @Html.ActionLink("Details", "Details", new { id=item.id },
                new { onclick = "return confirmation();", @class = "btn btn-primary"}) |
                @Html.ActionLink("Delete", "Delete", new {id=item.id },
                new { onclick = "return confirmation();", @class = "btn btn-danger"})
            </td>
        </tr>
}
    </tbody>
</table>

MVCproyecto/Views/Compra/Create.cshtml
@model MVCproyecto.Models.Compra

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Compra</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @*<div class="form-group">
                <label asp-for="id" class="control-label"></label>
                <input asp-for="id" class="form-control" />
                <span asp-validation-for="id" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="fecha" class="control-label"></label>
                <input asp-for="fecha" class="form-control" />
                <span asp-validation-for="fecha" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Usuario" class="control-label"></label>
                <input asp-for="Usuario" class="form-control" />
                <span asp-validation-for="Usuario" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Producto" class="control-label"></label>
                <input asp-for="Producto" class="form-control" />
                <span asp-validation-for="Producto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="cantidad" class="control-label"></label>
                <input asp-for="cantidad" class="form-control" />
                <span asp-validation-for="cantidad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="precio" class="control-label"></label>
                <input asp-for="precio" class="form-control" />
                <span asp-validation-for="precio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

MVCproyecto/Views/Compra/Delete.cshtml
@model MVCproyecto.Models.Compra

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Compra</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.fecha)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.fecha)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Usuario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Usuario)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Producto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Producto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.cantidad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.cantidad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.precio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.precio)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MVCproyecto/Views/Compra/Details.cshtml
@model MVCproyecto.Models.Compra

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Compra</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.fecha)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.fecha)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Usuario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Usuario)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Producto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Producto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.cantidad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.cantidad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.precio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.precio)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

MVCproyecto/Views/Compra/Edit.cshtml
@model MVCproyecto.Models.Compra

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Compra</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="id" class="control-label"></label>
                <input asp-for="id" class="form-control" readonly />
                <span asp-validation-for="id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="fecha" class="control-label"></label>
                <input asp-for="fecha" class="form-control" />
                <span asp-validation-for="fecha" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Usuario" class="control-label"></label>
                <input asp-for="Usuario" class="form-control" />
                <span asp-validation-for="Usuario" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Producto" class="control-label"></label>
                <input asp-for="Producto" class="form-control" />
                <span asp-validation-for="Producto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="cantidad" class="control-label"></label>
                <input asp-for="cantidad" class="form-control" />
                <span asp-validation-for="cantidad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="precio" class="control-label"></label>
                <input asp-for="precio" class="form-control" />
                <span asp-validation-for="precio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

MVCproyecto/Views/Compra/Index.cshtml
@model IEnumerable<MVCproyecto.Models.Compra>

@{
    ViewData["Title"] = "Compra Productos";
}

<h1>Compra Porductos</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.fecha)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Usuario)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Producto)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.cantidad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.precio)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.fecha)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Usuario)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Producto)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.cantidad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.precio)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
                @Html.ActionLink("Details", "Details", new { id=item.id }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.id })
            </td>
        </tr>
}
    </tbody>
</table>

MVCproyecto/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCproyecto</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
    <link rel="stylesheet" href="~/MVCproyecto.styles.css" asp-append-version="true" />
    <style>
        body {
            background: white;
        }

        div{
            color: white;
        }
        h1,p, h2, span, h3, h4, label{
            color: black
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="https://static.vecteezy.com/system/resources/thumbnails/005/601/776/small/pet-shop-logo-vector.jpg" alt="Logo" width="40" height="40" class="d-inline-block align-text-top">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cliente" asp-action="Index">Clientes</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Producto" asp-action="Index">Productos</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Compra" asp-action="Index">Compra</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            <p>
                2023 - MVCproyecto
            </p>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>